# Generated by Django 4.1.7 on 2023-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('kode_admin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=50)),
                ('password_admin', models.CharField(max_length=20)),
            ],
        ),
    ]
