# Generated by Django 4.1.7 on 2023-11-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admins_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('kode_gudang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_gudang', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KelompokBarang',
            fields=[
                ('kode_kelompok', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_kelompok', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatuanBarang',
            fields=[
                ('kode_satuan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_satuan', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
