# Generated by Django 4.2.5 on 2023-12-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gudang_kelompokbarang_satuanbarang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('kode_customers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_customers', models.CharField(max_length=120)),
                ('jenis_customers', models.CharField(max_length=120)),
                ('alamat_customers', models.CharField(max_length=120, null=True)),
                ('wa_customer', models.CharField(max_length=20, null=True)),
                ('email_customers', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataBarang',
            fields=[
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=200)),
                ('kelompok_barang', models.CharField(max_length=50)),
                ('jenis_barang', models.CharField(max_length=50)),
                ('satuan_barang_small', models.CharField(max_length=50)),
                ('satuan_barang_medium', models.CharField(max_length=50)),
                ('satuan_barang_large', models.CharField(max_length=50)),
                ('tgl_expire_barang', models.DateField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSupplier',
            fields=[
                ('kode_supplier', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=120, null=True)),
                ('alamat_supplier', models.CharField(max_length=120, null=True)),
                ('npwp_supplier', models.CharField(max_length=50, null=True)),
                ('tlp_supplier', models.CharField(max_length=13, null=True)),
                ('email_supplier', models.CharField(max_length=120, null=True)),
                ('wa_supplier', models.CharField(max_length=13, null=True)),
                ('nama_bank_supplier', models.CharField(max_length=20, null=True)),
                ('no_rek_supplier', models.CharField(max_length=20, null=True)),
                ('ket_supplier', models.CharField(max_length=250, null=True)),
                ('status_aktif_supplier', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HargaBarang',
            fields=[
                ('kode_harga', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kode_barang', models.CharField(max_length=20, null=True)),
                ('nama_barang', models.CharField(max_length=120)),
                ('harga_satuan_small', models.IntegerField()),
                ('harga_satuan_medium', models.IntegerField()),
                ('harga_satuan_large', models.IntegerField()),
                ('ppn_barang', models.IntegerField(null=True)),
                ('diskon_barang', models.IntegerField()),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('kode_jenis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisCustomers',
            fields=[
                ('kode_jenis_customers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_jenis_customers', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransactions',
            fields=[
                ('kode_sales', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('nama_customers', models.CharField(max_length=120, null=True)),
                ('kode_customers', models.CharField(max_length=20, null=True)),
                ('nama_sopir', models.CharField(max_length=120, null=True)),
                ('kode_sopir', models.CharField(max_length=20, null=True)),
                ('nama_barang', models.CharField(max_length=120, null=True)),
                ('kode_barang', models.CharField(max_length=20, null=True)),
                ('nama_satuan', models.CharField(max_length=120, null=True)),
                ('harga_barang', models.IntegerField(null=True)),
                ('quantity_sales', models.IntegerField(null=True)),
                ('diskon_sales', models.IntegerField(null=True)),
                ('biaya_pengiriman', models.IntegerField(null=True)),
                ('sub_total_sales', models.IntegerField(null=True)),
                ('grand_total_sales', models.IntegerField(null=True)),
                ('jenis_pembayaran', models.CharField(max_length=120, null=True)),
                ('total_pembayaran_sales', models.IntegerField(null=True)),
                ('sisa_tagihan', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sopir',
            fields=[
                ('kode_sopir', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_sopir', models.CharField(max_length=120)),
                ('alamat_sopir', models.CharField(max_length=120)),
                ('wa_sopir', models.CharField(max_length=20)),
                ('email_sopir', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StokBarang',
            fields=[
                ('kode_stok', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kode_barang', models.CharField(max_length=20, null=True)),
                ('nama_barang', models.CharField(max_length=120, null=True)),
                ('stok_satuan_small', models.CharField(max_length=20)),
                ('stok_satuan_medium', models.CharField(max_length=20)),
                ('stok_satuan_large', models.CharField(max_length=20)),
                ('nama_gudang', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmins',
            fields=[
                ('kode_superadmin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_superadmin', models.CharField(max_length=120)),
                ('password_superadmin', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarangSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_satuan_small', models.IntegerField(null=True)),
                ('quantity_satuan_medium', models.IntegerField(null=True)),
                ('quantity_satuan_large', models.IntegerField(null=True)),
                ('satuan_harga_small', models.IntegerField(null=True)),
                ('satuan_harga_medium', models.IntegerField(null=True)),
                ('satuan_harga_large', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.databarang')),
                ('kode_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasupplier')),
            ],
        ),
    ]
