# Generated by Django 4.2.5 on 2023-12-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customers_databarang_datasupplier_hargabarang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi_pembelian', models.CharField(max_length=120, null=True)),
                ('harga_pembelian', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('ppn_barang_transaksi', models.CharField(max_length=120, null=True)),
                ('diskon_transaksi', models.IntegerField(null=True)),
                ('biaya_pengiriman', models.IntegerField(null=True)),
                ('total_pembelian', models.IntegerField(null=True)),
                ('jenis_pembayaran', models.IntegerField(null=True)),
                ('total_pembayaran', models.IntegerField(null=True)),
                ('sisa_tagihan', models.IntegerField(null=True)),
                ('timestamp', models.DateField(null=True)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.databarang')),
                ('kode_satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.satuanbarang')),
                ('kode_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasupplier')),
            ],
        ),
    ]
