# Generated by Django 4.2.5 on 2023-12-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaksipembelian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipembelian',
            name='jenis_pembayaran',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
