# Generated by Django 4.2.5 on 2023-12-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transaksipembelian_jenis_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipembelian',
            name='sisa_tagihan',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
