# Generated by Django 4.2.5 on 2023-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_transaksipembelian_sisa_tagihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipembelian',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
