# Generated by Django 4.2.5 on 2023-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_transaksipembelian_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipembelian',
            name='status',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
