# Generated by Django 4.2.5 on 2023-12-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaksipembelian_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransactions',
            name='harga_barang',
        ),
        migrations.RemoveField(
            model_name='salestransactions',
            name='kode_barang',
        ),
        migrations.RemoveField(
            model_name='salestransactions',
            name='nama_barang',
        ),
        migrations.RemoveField(
            model_name='salestransactions',
            name='nama_satuan',
        ),
        migrations.RemoveField(
            model_name='salestransactions',
            name='quantity_sales',
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=120, null=True)),
                ('kode_barang', models.CharField(max_length=20, null=True)),
                ('nama_satuan', models.CharField(max_length=120, null=True)),
                ('harga_barang', models.IntegerField(null=True)),
                ('quantity_sales', models.IntegerField(null=True)),
                ('kode_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salestransactions')),
            ],
        ),
    ]
