# Generated by Django 4.2.5 on 2023-12-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_salestransactions_harga_barang_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailTransaksi',
        ),
    ]
