# Generated by Django 4.2.5 on 2023-12-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_detailtransaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='kode_satuan',
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='nama_satuan',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
