# Generated by Django 4.2.5 on 2023-12-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_detailtransaksi_kode_satuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='quantity_sales',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
