# Generated by Django 4.2.5 on 2023-12-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_detailtransaksi_quantity_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='kode_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salestransactions'),
        ),
    ]
