# Generated by Django 4.2.5 on 2023-12-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_detailtransaksi_kode_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='quantity_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stokbarang',
            name='stok_satuan_small',
            field=models.IntegerField(null=True),
        ),
    ]
