# Generated by Django 4.1.7 on 2023-12-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_detailtransaksi_quantity_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangsupplier',
            name='kode_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.databarang'),
        ),
    ]
