# Generated by Django 4.1.7 on 2023-12-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_barangsupplier_kode_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retails',
            fields=[
                ('kode_retail', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_retail', models.CharField(max_length=120)),
                ('alamat_retail', models.CharField(max_length=120)),
                ('wa_reatail', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
