# Generated by Django 4.1.7 on 2023-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_retails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retails',
            name='wa_reatail',
        ),
        migrations.AddField(
            model_name='retails',
            name='desc_retail',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='retails',
            name='wa_retail',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
