# Generated by Django 4.1.7 on 2024-01-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_retails_wa_reatail_retails_desc_retail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksipembelian',
            name='harga_pembelian',
        ),
        migrations.RemoveField(
            model_name='transaksipembelian',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaksipembelian',
            name='kode_barang',
        ),
        migrations.RemoveField(
            model_name='transaksipembelian',
            name='kode_satuan',
        ),
        migrations.RemoveField(
            model_name='transaksipembelian',
            name='ppn_barang_transaksi',
        ),
        migrations.RemoveField(
            model_name='transaksipembelian',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='transaksipembelian',
            name='kode_transaksi_pembelian',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satuan', models.CharField(max_length=120, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('ppn_barang_transaksi', models.CharField(max_length=120, null=True)),
                ('harga_total', models.IntegerField(null=True)),
                ('kode_barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.databarang')),
                ('kode_transaksi_pembelian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transaksipembelian')),
            ],
        ),
    ]
