# Generated by Django 4.1.7 on 2024-01-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_transaksipembelian_harga_pembelian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargabarang',
            name='harga_satuan_large',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hargabarang',
            name='harga_satuan_medium',
            field=models.IntegerField(null=True),
        ),
    ]
