# Generated by Django 4.1.7 on 2024-01-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_hargabarang_harga_satuan_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operasional',
            fields=[
                ('kode_operasional', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('lokasi_awal', models.CharField(max_length=120)),
                ('lokasi_tujuan', models.CharField(max_length=120)),
                ('jenis_transportasi', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
