# Generated by Django 4.1.7 on 2024-01-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_operasional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('kode_pengiriman', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('jalur_pengiriman', models.CharField(max_length=120)),
                ('biaya_pengiriman', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
