# Generated by Django 4.1.7 on 2024-01-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_pengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransactions',
            name='tagihan_awal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaksipembelian',
            name='tagihan_awal',
            field=models.IntegerField(null=True),
        ),
    ]
