# Generated by Django 4.1.7 on 2024-01-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_salestransactions_tagihan_awal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipembelian',
            name='sisa_tagihan',
            field=models.IntegerField(null=True),
        ),
    ]
